namespace SimpleEntityWithAutoGeneratedKey
{
    public static class SimpleEntityWithAutoGeneratedKeyConnectionClass
    {
        public static string GetConnectionName()
        {
            return "SimpleEntityWithAutoGeneratedKeyConnection";
        }

    }
}