using DomainFramework.Core;
using System;
using System.Collections.Generic;
using Utilities.Validation;

namespace SimpleEntityWithAutoGeneratedKey.SimpleEntityWithAutoGeneratedKeyBoundedContext
{
    public class SaveTestEntityInputDto : IInputDataTransferObject
    {
        public int TestEntityId { get; set; }

        public string Text { get; set; }

        public TestEntity.EnumerationType1 Enumeration1 { get; set; }

        public TypeValueInputDto TypeValue1 { get; set; }

        public UrlInputDto Url { get; set; }

        public SelectionCriteriaInputDto Distance { get; set; }

        public SelectionCriteriaInputDto Traffic { get; set; }

        public SelectionCriteriaInputDto Time { get; set; }

        public virtual void Validate(ValidationResult result)
        {
            Text.ValidateRequired(result, nameof(Text));

            Text.ValidateMaxLength(result, nameof(Text), 50);

            Enumeration1.ValidateRequired(result, nameof(Enumeration1));

            TypeValue1.Validate(result);

            Url.Validate(result);

            Distance?.Validate(result);

            Traffic?.Validate(result);

            Time?.Validate(result);
        }

    }
}