using DomainFramework.Core;
using System;
using System.Collections.Generic;
using Utilities.Validation;

namespace SimpleEntityWithAutoGeneratedKey.SimpleEntityWithAutoGeneratedKeyBoundedContext
{
    public class SelectionCriteriaInputDto : IInputDataTransferObject
    {
        public bool? Selected { get; set; }

        public string YesNoNotSure { get; set; }

        public virtual void Validate(ValidationResult result)
        {
            YesNoNotSure.ValidateMaxLength(result, nameof(YesNoNotSure), 1);
        }

    }
}