using DomainFramework.Core;
using System;
using System.Collections.Generic;
using Utilities.Validation;

namespace SimpleEntityWithAutoGeneratedKey.SimpleEntityWithAutoGeneratedKeyBoundedContext
{
    public class UrlInputDto : IInputDataTransferObject
    {
        public string Value { get; set; }

        public virtual void Validate(ValidationResult result)
        {
            Value.ValidateNotEmpty(result, nameof(Value));

            Value.ValidateMaxLength(result, nameof(Value), 255);
        }

    }
}