using DomainFramework.Core;
using System;
using System.Collections.Generic;

namespace SimpleEntityWithAutoGeneratedKey.SimpleEntityWithAutoGeneratedKeyBoundedContext
{
    public class SelectionCriteriaOutputDto : IOutputDataTransferObject
    {
        public bool? Selected { get; set; }

        public bool Yes { get; set; }

        public bool No { get; set; }

        public bool NotSure { get; set; }

    }
}