using DomainFramework.Core;
using System;
using System.Collections.Generic;

namespace SimpleEntityWithAutoGeneratedKey.SimpleEntityWithAutoGeneratedKeyBoundedContext
{
    public class TestEntityOutputDto : IOutputDataTransferObject
    {
        public int TestEntityId { get; set; }

        public string Text { get; set; }

        public bool IsActive { get; set; }

        public bool IsEnumeration1Element1 { get; set; }

        public bool IsEnumeration1Element2 { get; set; }

        public bool IsEnumeration1Element3 { get; set; }

        public TypeValueOutputDto TypeValue1 { get; set; }

        public UrlOutputDto Url { get; set; }

        public SelectionCriteriaOutputDto Distance { get; set; }

        public SelectionCriteriaOutputDto Traffic { get; set; }

        public SelectionCriteriaOutputDto Time { get; set; }

    }
}