using DomainFramework.Core;
using System;
using System.Collections.Generic;

namespace SimpleEntityWithAutoGeneratedKey.SimpleEntityWithAutoGeneratedKeyBoundedContext
{
    public class UrlOutputDto : IOutputDataTransferObject
    {
        public string Value { get; set; }

    }
}