using DomainFramework.Core;
using System;
using System.Collections.Generic;

namespace SimpleEntityWithAutoGeneratedKey.SimpleEntityWithAutoGeneratedKeyBoundedContext
{
    public class TestEntity : Entity<int>
    {
        public enum EnumerationType1
        {
            Element1 = 1,
            Element2 = 2,
            Element3 = 3
        }

        public string Text { get; set; }

        public EnumerationType1 Enumeration1 { get; set; }

        /// <summary>
        /// Whether this record is active
        /// </summary>
        public bool IsActive { get; set; }

        public int CreatedBy { get; set; }

        public DateTime CreatedDateTime { get; set; }

        public Url Url { get; set; }

        public TypeValue TypeValue1 { get; set; }

        public SelectionCriteria Distance { get; set; }

        public SelectionCriteria Traffic { get; set; }

        public SelectionCriteria Time { get; set; }

    }
}