using DomainFramework.Core;
using System;
using System.Collections.Generic;

namespace SimpleEntityWithAutoGeneratedKey.SimpleEntityWithAutoGeneratedKeyBoundedContext
{
    public class SelectionCriteria : ValueObject<SelectionCriteria>
    {
        public bool? Selected { get; set; }

        public string YesNoNotSure { get; set; }

        public override bool IsEmpty() => 
            Selected == default(bool?) && YesNoNotSure == default(string);

        protected override IEnumerable<object> GetFieldsToCheckForEquality() => 
            new List<object>
            {
                Selected,
                YesNoNotSure
            };

    }
}