using DomainFramework.Core;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace SimpleEntityWithAutoGeneratedKey.SimpleEntityWithAutoGeneratedKeyBoundedContext
{
    [TypeConverter(typeof(UrlTypeConverter))]
    public class Url : ValueObject<Url>
    {
        /// <summary>
        /// The value of the URL
        /// </summary>
        public string Value { get; set; }

        public override bool IsEmpty() => 
            Value == default(string);

        protected override IEnumerable<object> GetFieldsToCheckForEquality() => 
            new List<object>
            {
                Value
            };

        public static bool TryParse(string s, out Url result)
        {
            if (string.IsNullOrWhiteSpace(s))
            {
                result = new Url
                {
                    Value = null
                };
            }

            result = new Url
            {
                Value = s
            };

            return true;
        }

    }
}